### ISSUE TITLE
where is the included addon ofxDeferredParams?

### ISSUE THREAD

**Issue by moebiussurfing** [nama-gatsuo/SequenceEditor#1]
thanks for sharing this. I am fighting for months with old ofxSequencer.
any tips around to get this working on 0.10?
I am getting this errors:
```
Models.h
Error:(7, 27) unknown type name 'UCHAR'
Error:(7, 43) unknown type name 'UCHAR'
Error:(7, 52) unknown type name 'UCHAR'
Error:(11, 2) unknown type name 'UCHAR'
Error:(12, 2) unknown type name 'UCHAR'
Error:(13, 2) unknown type name 'UCHAR'
Error:(19, 12) unknown type name 'UCHAR'
Error:(19, 22) unknown type name 'UCHAR'
Error:(19, 36) unknown type name 'UCHAR'
Error:(19, 45) unknown type name 'UCHAR'
Error:(19, 54) unknown type name 'UCHAR'
Error:(19, 70) unknown type name 'UCHAR'
Error:(19, 86) unknown type name 'UCHAR'
Error:(31, 2) unknown type name 'UCHAR'
Error:(32, 2) unknown type name 'UCHAR'
Error:(33, 2) unknown type name 'UCHAR'
Error:(34, 2) unknown type name 'UCHAR'
Error:(35, 2) unknown type name 'UCHAR'
Error:(36, 2) unknown type name 'UCHAR'
Error:(7, 27) unknown type name 'UCHAR'
Error:(7, 43) unknown type name 'UCHAR'
Error:(7, 52) unknown type name 'UCHAR'
Error:(11, 2) unknown type name 'UCHAR'
Error:(12, 2) unknown type name 'UCHAR'
Error:(13, 2) unknown type name 'UCHAR'
Error:(19, 12) unknown type name 'UCHAR'
Error:(19, 22) unknown type name 'UCHAR'
Error:(19, 36) unknown type name 'UCHAR'
Error:(19, 45) unknown type name 'UCHAR'
Error:(19, 54) unknown type name 'UCHAR'
Error:(19, 70) unknown type name 'UCHAR'
Error:(19, 86) unknown type name 'UCHAR'
Error:(31, 2) unknown type name 'UCHAR'
Error:(32, 2) unknown type name 'UCHAR'
Error:(33, 2) unknown type name 'UCHAR'
Error:(34, 2) unknown type name 'UCHAR'
Error:(35, 2) unknown type name 'UCHAR'
Error:(36, 2) unknown type name 'UCHAR'
Error:(7, 27) unknown type name 'UCHAR'
Error:(7, 43) unknown type name 'UCHAR'
Error:(7, 52) unknown type name 'UCHAR'
Error:(11, 2) unknown type name 'UCHAR'
Error:(12, 2) unknown type name 'UCHAR'
Error:(13, 2) unknown type name 'UCHAR'
Error:(19, 12) unknown type name 'UCHAR'
Error:(19, 22) unknown type name 'UCHAR'
Error:(19, 36) unknown type name 'UCHAR'
Error:(19, 45) unknown type name 'UCHAR'
Error:(19, 54) unknown type name 'UCHAR'
Error:(19, 70) unknown type name 'UCHAR'
Error:(19, 86) unknown type name 'UCHAR'
Error:(31, 2) unknown type name 'UCHAR'
Error:(32, 2) unknown type name 'UCHAR'
Error:(33, 2) unknown type name 'UCHAR'
Error:(34, 2) unknown type name 'UCHAR'
Error:(35, 2) unknown type name 'UCHAR'
Error:(36, 2) unknown type name 'UCHAR'
Error:(7, 27) unknown type name 'UCHAR'
Error:(7, 43) unknown type name 'UCHAR'
Error:(7, 52) unknown type name 'UCHAR'
Error:(11, 2) unknown type name 'UCHAR'
Error:(12, 2) unknown type name 'UCHAR'
Error:(13, 2) unknown type name 'UCHAR'
Error:(19, 12) unknown type name 'UCHAR'
Error:(19, 22) unknown type name 'UCHAR'
Error:(19, 36) unknown type name 'UCHAR'
Error:(19, 45) unknown type name 'UCHAR'
Error:(19, 54) unknown type name 'UCHAR'
Error:(19, 70) unknown type name 'UCHAR'
Error:(19, 86) unknown type name 'UCHAR'
Error:(31, 2) unknown type name 'UCHAR'
Error:(32, 2) unknown type name 'UCHAR'
Error:(33, 2) unknown type name 'UCHAR'
Error:(34, 2) unknown type name 'UCHAR'
Error:(35, 2) unknown type name 'UCHAR'
Error:(36, 2) unknown type name 'UCHAR'
main.cpp
Error:too many errors emitted, stopping now [-ferror-limit=]
ofApp.cpp
Error:too many errors emitted, stopping now [-ferror-limit=]
UIManager.cpp
Error:too many errors emitted, stopping now [-ferror-limit=]
UIState.cpp
Error:too many errors emitted, stopping now [-ferror-limit=]
```

**Comment by moebiussurfing** [comment]
hey @nama-gatsuo , 
I suspect that you are using Windows and here in MacOs it seems do not uses UCHAR. ULONG, UINT... never seen this types before. 

It seems to pass some errors adding this to the Sequencer.h:
typedef int UINT;
typedef long ULONG;
And to the Models.h:
typedef int UCHAR;

Now I have the previous error about VisualApp.h Error:(6, 10) 'ofxDeferredParams.h' file not found 

And UIManager.cpp
Error:(59, 2) call to 'PushStyleColor' is ambiguous
Error:(60, 2) call to 'PushStyleColor' is ambiguous
Error:(69, 3) call to 'PushStyleColor' is ambiguous
Error:(70, 3) call to 'PushStyleColor' is ambiguous
Error:(105, 3) call to 'PushStyleColor' is ambiguous
Error:(106, 3) call to 'PushStyleColor' is ambiguous
Error:(120, 3) call to 'PushStyleColor' is ambiguous
Error:(121, 3) call to 'PushStyleColor' is ambiguous

I'll try to isolate the sequencer stuff only, without visualisations, to try to make it work...
Any help is welcome
cheers

**Comment by moebiussurfing** [comment]
hey @nama-gatsuo , I am sorry for insist you about this,,,, 

but is there any chance that you can say some tips to isolate your step sequencer from here?
I am super stuck here... and I don't know where to start from.

sorry again if I am boring you. I'll post here if I make some progress.

**Comment by moebiussurfing** [comment]
My last try before abandon my tries,,,

I went to your first commit (to have minimal expression without ofxImGui, visual blocks..etc) 
and I just added to the .h classes where uses this types... :
```
typedef int UCHAR;
typedef int UINT;
typedef int USHORT;
typedef long ULONG;
```

I am getting this error that I don't know how to solve:
```
ScoreManager.cpp
Error:(57, 8) non-const lvalue reference to type 'pair<...>' cannot bind to a temporary of type 'pair<...>'
	auto& beatAndBar = calcEnd(note.beatNum, note.barNum, note.duration);
```

**Comment by nama-gatsuo** [comment]
Sorry to have kept you waiting! I just committed some update to fix your trouble.
ofxDeferredParams was deleted and renewed as ofxDeferredHelper ( https://github.com/nama-gatsuo/ofxDeferredHelper ) .

Now the master branch should be able to be compiled.

**Comment by nama-gatsuo** [comment]
As you know, the types like UCHAR, ULONG, and UINT are just syntax sugar Visual C++ provides. I also update to use the default type name.

**Comment by moebiussurfing** [comment]
hey @nama-gatsuo , thanks a lot for put your hands on this!

now I am getting this:
```
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:139:5: Non-constant-expression cannot be narrowed from type 'int' to 'unsigned char' in initializer list
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:139:5: Insert an explicit cast to silence this issue
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:139:8: Non-constant-expression cannot be narrowed from type 'int' to 'unsigned char' in initializer list
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:139:8: Insert an explicit cast to silence this issue
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:140:5: Non-constant-expression cannot be narrowed from type 'int' to 'unsigned char' in initializer list
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:140:5: Insert an explicit cast to silence this issue
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:141:5: Non-constant-expression cannot be narrowed from type 'int' to 'unsigned char' in initializer list
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:141:5: Insert an explicit cast to silence this issue
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:142:5: Non-constant-expression cannot be narrowed from type 'int' to 'unsigned char' in initializer list
/Users/myUser/Documents/openFrameworks/apps/myApps/SequenceEditor/src/controller/UIState.cpp:142:5: Insert an explicit cast to silence this issue
```

I tried to "be lucky" doing the Xcode suggested auto fixes (cast..), and added some other typedef int UINT..etc but stills not compiling.

**Comment by nama-gatsuo** [comment]
Got it, now I checked on mac. The main issues are coming from using `unsigned char`. At windows, the compiler can implicitly cast `int` to `unsigned char` and vice verse. The simplest solution is to replace all `unsigned char` to `int`. I don't know it can be done easily, but I gonna try when I have time.

**Comment by moebiussurfing** [comment]
just in case can 'help' in some way... 
After changing all unsigned char to int, only the 3 above errors persist. 

There's something on here:
```
auto& beatAndBar = calcEnd(note.x, note.barNum, note.duration);
...
return std::make_pair((int)endBeat, (int)endBar);
```

```
ScoreManager.cpp
Error:(113, 8) non-const lvalue reference to type 'pair<...>' cannot bind to a temporary of type 'pair<...>'
Error:(162, 8) non-const lvalue reference to type 'pair<...>' cannot bind to a temporary of type 'pair<...>'
Error:(176, 8) non-const lvalue reference to type 'pair<...>' cannot bind to a temporary of type 'pair<...>'
...
std::pair<int, int> ScoreManager::calcEnd(int startBeat, int startBar, int duration) const {

	int endBeat = startBeat + duration;
	int endBar = startBar;
	if (endBeat >= beat) {
		endBeat -= beat;
		endBar++;
		if (endBar >= barCount) {
			endBar -= barCount;
		}
	}

	return std::make_pair((int)endBeat, (int)endBar);
}
```

**Comment by ottonove** [comment]
@moebiussurfing 
How about this?
```auto& beatAndBar = calcEnd(note.x, note.barNum, note.duration);```
to
``` const auto& beatAndBar = calcEnd(note.x, note.barNum, note.duration);```
added "const".

**Comment by ottonove** [comment]
@nama-gatsuo 

This project is so cool!!
I longed for this and tried build.

Build was successful, but there was no sound.

I added the code to check the MIDI note number as follows.

```src/model/MidiSender.h```

```
void sendMidiOn(unsigned char ch, unsigned char midiNum, unsigned char velocity) {
  ofLogNotice() << "note: " << midiNum; //add
  midiOut.sendNoteOn(ch, midiNum, velocity);
}
```

Here is the output log
 
```
[notice ] note: )
[notice ] note: +
[notice ] note: *
[notice ] note: (
[notice ] note: +
[notice ] note: -
[notice ] note: .
```

Is this correct?

https://github.com/ottonove/SequenceEditorClone/tree/master

**Comment by moebiussurfing** [comment]
thanks @ottonove . yes, this project it's cool! 
It would be nice to have an isolated sequencer/piano roll like this as an addon...

Do you have any virtual midi synth installed? It worked here on Windows playing and sounding against the system general midi synth. Just in case, if I am not wrong, the sequencer just plays midi notes, not sound...

**Comment by nama-gatsuo** [comment]
Yes. Thanks, @moebiussurfing is right !

The app only provides an editor, visualization and midi emitter. It is supposed to have virtual midi router and DAW on your machine. 
* mac has [built-in router](https://support.apple.com/ja-jp/guide/audio-midi-setup/ams875bae1e0/mac)
* for win, [Loop Midi](https://www.tobias-erichsen.de/software/loopmidi.html) worked.

The app emits midi notes and pass to DAW through the router. Sorry for lack of doc.

**Comment by ottonove** [comment]
@moebiussurfing @nama-gatsuo  thanks!!

I don't install midi synth yet, I try it.

Resolved about above log. There was an answer at this url.

https://stackoverflow.com/questions/14644716/how-to-output-a-character-as-an-integer-through-cout

```ofLogNotice() << "note: " << +midiNum;```

When "+" was added before midiNum, the numerical value was displayed.
